destination: _site

plugins:
  - jekyll-seo-tag
  - jekyll-tailwindcss
  - jekyll-sitemap

tailwindcss:
  css_path: "./_tailwind.css" # this is the default location

# jekyll-seo-tag configuration
title: Istvan Hoka
description: Software Engineer & Startup CTO with 20+ years building scalable systems and leading technical transformation.
author: Istvan Hoka
url: http://www.ihoka.me
google_analytics: G-77ZXM9KF74

social:
  name: Istvan Hoka
  links:
    - https://github.com/ihoka
    - https://www.linkedin.com/in/ihoka/
    - https://x.com/ihoka
    - https://www.youtube.com/@ihoka

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# to override the default setting.
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - mise.toml
  - TODO.md
  - CNAME
